### ISSUE TITLE
CI/CD tweaks - Auto release using github actions

### ISSUE THREAD

**Issue by kobenguyent** [uibakery/axios-http2-adapter#8]
```
on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@example.com"
      - name: Install deps
        run: npm i
      - name: Run tests
        run: npm run test
      - name: Build the app
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm run build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # push the version changes to GitHub
      - run: git add package.json package-lock.json && git commit -m'update version' && git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
